apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: latency-demo
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      nodeSelector:
        kubernetes.io/hostname: controlplane
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports: [{ containerPort: 80 }]
          volumeMounts:
            - name: static
              mountPath: /usr/share/nginx/html
      volumes:
        - name: static
          configMap:
            name: frontend-static
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: latency-demo
spec:
  type: ClusterIP
  selector: { app: frontend }
  ports:
    - name: http
      port: 80
      targetPort: 80
