apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
  namespace: latency-demo
spec:
  replicas: 1
  selector: { matchLabels: { app: relay } }
  template:
    metadata:
      labels: { app: relay }
    spec:
      nodeSelector:
        kubernetes.io/hostname: node01
      containers:
        - name: relay
          image: python:3.11-slim
          ports: [{ containerPort: 8080 }]
          env:
            - name: BACKEND_URL
              value: http://backend-svc:5000
            - name: CPU_AFFINITY
              value: "0"
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "2"
          volumeMounts:
            - name: code
              mountPath: /app
          command:
            - /bin/sh
            - -c
            - |
              pip install --no-cache-dir flask requests flask-cors && \
              python /app/relay.py
      volumes:
        - name: code
          configMap:
            name: relay-code
---
apiVersion: v1
kind: Service
metadata:
  name: relay-svc
  namespace: latency-demo
spec:
  type: NodePort
  selector: { app: relay }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081
