apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-code
  namespace: latency-demo
data:
  backend.py: |
    import time
    import hashlib
    from flask import Flask, request, jsonify

    app = Flask(__name__)

    def tiny_cpu(work=30_000):
        x = 0
        for _ in range(work):
            x = (x * 1103515245 + 12345) % 2**31
            hashlib.md5(str(x).encode()).hexdigest()
        return x

    @app.route("/process", methods=["POST"])
    def process():
        t0 = time.time()
        _ = tiny_cpu(40_000)
        t1 = time.time()
        req = request.get_json(force=True, silent=True) or {}
        return jsonify({
            "backend_time_ms": round((t1 - t0) * 1000),
            "backend_finished_at": time.strftime("%Y-%m-%d %H:%M:%S"),
            "echo": req
        })

    @app.route("/ping")
    def ping():
        return jsonify({"ok": True})

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=5000)
