apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-hog
  namespace: latency-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cpu-hog
  template:
    metadata:
      labels:
        app: cpu-hog
    spec:
      terminationGracePeriodSeconds: 1
      nodeSelector:
        kubernetes.io/hostname: node01
      containers:
        - name: hog
          image: python:3.11-slim
          resources:
            requests:
              cpu: "700m"
            limits:
              cpu: "1"
          env:
            - name: HOG_PROCS
              value: "1"
          command: ["/bin/sh","-c"]
          args:
            - |
              python - <<'PY'
              import multiprocessing
              import os
              def burn():
                  x = 0
                  while True:
                      x = (x * 1664525 + 1013904223) & 0xffffffff
              procs = int(os.getenv("HOG_PROCS", "1") or "1")
              ps = []
              for _ in range(procs):
                  p = multiprocessing.Process(target=burn, daemon=True)
                  p.start()
                  ps.append(p)
              for p in ps:
                  p.join()
              PY
