apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs
  namespace: latency-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs
  template:
    metadata:
      labels:
        app: cs
    spec:
      nodeSelector:
        kubernetes.io/hostname: node01
      containers:
        - name: cscontainer
          image: ubuntu:24.04
          resources:
            requests:
              cpu: "200m"
          env:
            - name: CS_SWITCH
              value: "8192"           # 上限内
            - name: CS_FUTEX
              value: "4096"           # 上限内（必要なら増減）
            - name: OPS
              value: "100000000"      # 1e8（上限）
            - name: DURATION
              value: "24h"
          command: ["/bin/bash","-lc"]
          args:
            - |
              set -e
              apt-get update -y >/dev/null
              apt-get install -y --no-install-recommends stress-ng >/dev/null
              [ -n "${AFFINITY}" ] && export TASKSET="taskset -c ${AFFINITY}" || export TASKSET=""
              exec ${TASKSET} stress-ng \
                --switch ${CS_SWITCH} --switch-ops ${OPS} \
                --futex  ${CS_FUTEX}  --futex-ops  ${OPS} \
                --metrics-brief \
                --timeout ${DURATION}
